inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数上限
LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'app/models/cal_consumption.rb'
    - "app/models/chat.rb"
    - "app/controllers/cal_balances_controller.rb"
    - "app/controllers/cal_consumptions_controller.rb"
    - "app/controllers/data_controller.rb"
    - "app/helpers/data_helper.rb"
    - "spec/system/after_login_spec.rb"
    - "spec/requests/users_autentications_spec.rb"